### ISSUE TITLE
Issue with create incident : err 2002

### ISSUE THREAD

**Issue by sudhishkasabaramesh** [PagerDuty/pagerduty-api-python-client#61]
I am using `pypd==1.1.0`.

I was able to create PD incident correctly, and my integrations with other systems was working perfectly.

As of this week, I have been having issues where I hit this error:
```
pypd.errors.BadRequest: BadRequest (2002): Arguments Caused Error - Service not found
```

Upon checking about `2002` error, I just see that `Arguments Caused Error` on the PD website [[reference_link_1](https://v2.developer.pagerduty.com/docs/errors) & [reference_link_2](https://v1.developer.pagerduty.com/documentation/rest/errors)]. Obviously the error message is NOT very helpful to figure out whats causing the problems at my end :|.

Here is a sample code which I am using to make this work (which was working earlier): 
```
import pypd
import os
import logging


class NotifierHook():

    def __init__(self):
        self.pagerduty_api_key = os.getenv("PAGERDUTY_API_KEY", "XXXXXXXX") # defaults to XXXXXXXX if the env variable is NOT set

    def _notify_pagerduty(self, service_id, title, message):
        try:
            pypd.api_key = self.pagerduty_api_key
            pagerduty_response = pypd.Incident.create(
                data={
                    'type': 'incident',
                    'title': title,
                    'service': {
                        'type': 'service_reference',
                        'id': service_id,
                    },
                    'body': {
                        'type': 'incident_body',
                        'details': message,
                    }
                }, add_headers={
                    "from": "XXXX@XXXX.com"
                }
            )
            logging.info(pagerduty_response)
        except Exception as ex:
            print(pagerduty_response)
            msg = "PagerDuty API call failed ({})".format(ex)
            logging.error(msg)


NotifierHook()._notify_pagerduty(service_id="XXXX", message="message", title="title")
```

The stack trace looks like this : 
```
Traceback (most recent call last):
  File "/foo/test.py", line 28, in _notify_pagerduty
    "from": "XXXX@XXXX.com"
  File "/foo/lib/python3.6/site-packages/pypd/models/entity.py", line 472, in create
    add_headers=add_headers,
  File "/foo/python3.6/site-packages/pypd/mixins.py", line 123, in request
    **kwargs
  File "/foo/python3.6/site-packages/pypd/mixins.py", line 72, in _do_request
    return self._handle_response(requests_method(*args, **kwargs))
  File "/foo/lib/python3.6/site-packages/pypd/mixins.py", line 48, in _handle_response
    raise BadRequest(response.status_code, response.text)
pypd.errors.BadRequest: BadRequest (2002): Arguments Caused Error - Service not found
```

------

EDIT#1

I have replaced all passwords, keys, emails & folders with `XXXX` or `foo` in the details above. If you are resting that code, pls replace those with your details.

**Comment by sudhishkasabaramesh** [comment]
This was an API key expiry issue.

I think this should change to a BUG ... because after changing my API key .. things started to work.

**Comment by bzmw** [comment]
Hey there, 
Thanks for your contribution but we decided to deprecate this project. Please use [PDPyras](https://github.com/PagerDuty/pdpyras) instead.
